name: HyperExtension Markup Language

on: [push]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build HEML
        run: cargo build --release

      - name: Upload HEML Binary
        uses: actions/upload-artifact@v4
        with:
          name: heml-windows-binary
          path: target/release/heml.exe
