name: HyperExtension Markup Language

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    name: Compile Windows Binary
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Stable Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build HEML
        run: cargo build --release

      - name: Archive Production Binary
        uses: actions/upload-artifact@v4
        with:
          name: heml-v0.1.0-windows-x64
          path: target/release/heml.exe
